name: Deploy Website Manga Reader Personal to Infinity Free App via FTP

on:
  push:
    branches:
      - master  # Menjalankan aksi setiap push ke branch master

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v6

    - name: Deploy via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local_path: './*'
        remote_path: '/mangareader.infinityfreeapp.com/htdocs/'
        